language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

before_install:
  - composer self-update
  - composer clear-cache

install:
  - travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest

script:
  - ./vendor/bin/phpunit --no-configuration ./test

notifications:
  email: false
